// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    donate
    (
        init => init
        upgrade => upgrade
        addKnownToken => add_known_token
        removeKnownToken => remove_known_token
        addKnownChain => add_known_chain
        removeKnownChain => remove_known_chain
        sendToken => send_token
        execute => execute
        gateway => gateway
        known_tokens => known_tokens
        known_chains_addresses => known_chains_addresses
        known_chains_names => known_chains_names
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
